# Generated by Django 4.1.4 on 2023-12-19 18:33

from django.db import migrations, models
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default='logo.jpeg', max_length=255, null=True, upload_to=network.models.get_profile_image_filepath),
        ),
    ]
