# Generated by Django 4.1.4 on 2023-12-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_account_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='file_type',
            field=models.CharField(choices=[('image', 'image'), ('video', 'video'), ('other', 'other')], default=False, max_length=256),
        ),
    ]
