# Generated by Django 4.1.4 on 2023-12-20 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_account_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='file_type',
        ),
    ]
