# Generated by Django 4.1.4 on 2023-12-20 17:16

from django.db import migrations, models
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_remove_account_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default=network.models.get_default_profile_image, max_length=255, null=True, upload_to=network.models.get_profile_image_filepath),
        ),
    ]
